services:
  games-service:
    image: mcr.microsoft.com/devcontainers/java:21
    hostname: games-service.local
    volumes:
      -  ..:/src:cached
      -  $HOME/.m2:/home/vscode/.m2:cached
    working_dir: /src 
    ports:
      - "${app_port}:8080"
      - "${app_debug_port}:8000"
    depends_on:
      - db
    command: >
      bash -c "sleep infinity"
    networks:
      game-service-net:

  adminer:
    image: adminer:5.0.4
    restart: always
    ports:
      - ${adminer_port}:8080
    depends_on:
      - db
    networks:
      game-service-net:


      
  db:
    image: postgres:17.5-alpine3.22
    hostname: db.local
    restart: always
    environment:
      - POSTGRES_USER=${db_user} #postgres
      - POSTGRES_PASSWORD=${db_password} #postgres
      - POSTGRES_DB=${db_name} #fritzbox
    ports:
      - "${db_port}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      game-service-net:
  # https://docs.postgrest.org/en/v12/explanations/install.html#containerized-postgrest-and-db-with-docker-compose
  postgrest:
    image: postgrest/postgrest:latest
    restart: always
    ports:
      - "${postgrest_port}:3000"
    environment:
      PGRST_DB_URI: "postgres://${db_user}:${db_password}@db.local:5432/${db_name}"
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:${postgrest_port}
      #PGRST_DB_ANON_ROLE: "web_anon"
      #PGRST_DB_SCHEMA: "public"
      PGRST_JWT_SECRET: "reallyreallyreallyreallyverysafe"
    networks:
      game-service-net:  
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "${postgrest_openapi_port}:8080"
    expose:
      - "${postgrest_openapi_port}:8080"
    environment:
      API_URL: http://localhost:${postgrest_port}

networks:
  game-service-net:

volumes:
  pg_data: 
    driver: local