name: build and test spring-api

on:
  push:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    name: build and deploy spring-api
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk 21
        uses: actions/setup-java@v3
        with:
         distribution: 'corretto'
         java-version: 21

      - name: unit tests & JaCoCo report
        run: game-service/mvnw package --file game-service/pom.xml

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
            path: './game-service/target/site/jacoco/'
      - name: Deploy JaCoCo report to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  

