name: build and test spring-api

on:
  workflow_run:
    workflows: [build and deploy spring-apiXXX]
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    name: deploy JaCoCo report to Project website
    runs-on: ubuntu-24.04
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
            # Upload the coverage directory from the repository
            path: './game-service/target/site/jacoco/'
      - name: Deploy JaCoCo report to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          
  

